Add bookings
ArchieBar/java-shareit pull request #2
Opened 2024-04-23 20:21 UTC by ArchieBar

В общем, я наконец добрался до проекта, но там много косяков... Не успеваю нормально сделать

2024-04-25 02:02 UTC, dgumich requested changes

2024-04-25 02:02 UTC, dgumich commented on src/main/java/ru/practicum/shareit/booking/model/state/StringToStateConverter.java
> +    public State convert(String source) {
А зачем нам конвертер из стринги в энам? Спринг сделает тоже самое, в чём профит данного конвертера? Только в другом выбрасываемом исключении?

2024-04-25 07:36 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryJpa.java
> +    @Query("SELECT i FROM Item i WHERE i.owner.id = ?1")
Это по моему я первый Query писал, смотрел как он работает :)

2024-04-25 07:37 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJpa.java
> +    private ItemRepositoryJpa itemRepository;
Вот была у меня такая мысль, касательно внедрения бинов. Не помню почему по итогу решил сделать через поля. Исправлю

2024-04-25 07:40 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/booking/model/state/StringToStateConverter.java
> +    public State convert(String source) {
Это я изначально принимал в аргументах методов контроллера State а не строку и нужен был конвертер как я понял. Но из за того, но он толи не работал как надо. То ли проблема с исключением была - отказался этой затеи и начал принимать строку, а класс забыл удалить. Исправлю

2024-04-25 07:41 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @NotNull
Исправил

2024-04-25 07:42 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.createComment(commentDto, itemId, userId);
В попыхах писал, добавлю.

2024-04-25 07:43 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.createComment(commentDto, itemId, userId);
Исправил

2024-04-25 07:46 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJpa.java
> +@Service("ItemServiceJpa")
Исправил

2024-04-25 08:03 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJpa.java
> +    private ItemRepositoryJpa itemRepository;
Исправил

2024-04-25 08:05 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/model/item/dto/ItemWithBooking.java
> +public class ItemWithBooking {
Исправил

2024-04-25 08:05 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/user/service/UserServiceJpa.java
> +    // Не уверен, нужно ли проверять на существование пользователя по ID перед удалением
Прочитал

2024-04-25 08:06 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/user/service/UserServiceJpa.java
> +        return UserMapper.toUserDto(
Исправил

2024-04-25 08:09 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/user/model/dto/UserDto.java
> +    // Вынести в отдельный интерфейс
Вынес в отдельный интерфейс, но не знал, куда его лучше вынести - вынес в общую папку в marker.Marker

2024-04-25 08:11 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    /*
А если использовать аннотации @Validated и @Valid в сервисе? Читал одну статью в которой говорится о том, что это лучше, т.к. иногда сервисы могут передавать данные между собой.

2024-04-25 08:16 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage(), e.getMessage());
Залогировал

2024-04-25 08:16 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/booking/model/state/StringToStateConverter.java
> +    public State convert(String source) {
Удалил класс

2024-04-26 02:20 UTC, dgumich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    /*
Зависит от проекта. Зачем нужна валидация? Потому что могут прислать что-то косячное. В мире разработки программисты доверяют друг другу. Ну или делают вид, что доверяют=) Поэтому сервисы, которые передают данные друг другу, предполагается, работают с валидными данными. И пишут их хорошие программисты. 
А вот что может прийти из вне, особенно от пользователей(или фронта=)) - вот там нужно быть на чеку. Поэтому чаще всего, проверяют такие данные и стараются сделать как можно раньше (это и логично). 
В реальности же всё зависит от проекта, исторически так сложилось, тим лида и  тд тп=)

2024-04-26 02:40 UTC, dgumich requested changes

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/booking/model/BookingMapper.java
> +                booking.getBooker().getId(),
В реальном проекте это потенциальное место NPE. Пишешь логику, думаешь, что бронирование же не может быть без того, кто забронировал. А потом оп, и попадается такая запись=) Я к тому, что логика маперов, чаще всего, полна проверок null, а не просто вызов конструктора со всеми параметрами.

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllBookingByItemOwnerIdAndEndTimeBeforeAndStatus(Long userId, LocalDateTime time, Status status);
Надеюсь, оценил, что дает нам сприг с его "магией"?=)

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new InvalidArgumentStateException(state);
А зачем нам ловить рантайм исключение, после этого выбрасывать своё? Мы же сразу в хендлере можем ловить IllegalArgumentException

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/model/comment/CommentDto.java
> +    @NotBlank
Одна аннотация более строгая, чем другая. Так что можно обойтись только ей. Советую глянуть доки=)

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/model/item/Item.java
> +    @NotBlank
Аналогично и здесь не нужно 2 аннотации, достаточно одной.

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/model/item/Item.java
> +    private String description;
Кстати, на некоторых проектах, названия столбцов указывают для всех полей. Даже когда оно простое и никак не поменяется (типа name/name). Имей это в виду и не удивляйся если что.

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJpa.java
> +    private final ItemRepositoryJpa itemRepository;
Внедрять через поля можно. Но спринг советуют через конструктор. 
В общем будь готов к любому варианту (даже через сеттер).

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceJpa.java
> +        return ItemMapper.toItemDto(itemRepository.save(
Честно говоря, читать такой код очень сложно.
Лучше вынести в переменные, новые строки, методы. 
В реальном проекте попросят переписать такое=)

2024-04-26 02:40 UTC, dgumich commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    // А как мне отловить это уникальное исключение?
Как уникальное исключение? То что емайл уникальный? Не получится сохранить пользователя с уже существующим емйлом. потому что БД исключение, что такой емйл уже есть.

2024-05-02 09:11 UTC, merged