Add item requests
ArchieBar/java-shareit pull request #4
Opened 2024-05-02 09:45 UTC by ArchieBar

2024-05-03 17:19 UTC, dgumich requested changes

2024-05-03 17:19 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
Добавь @Autowired, что бы всё было в одном стиле=)

2024-05-03 17:19 UTC, dgumich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +         * Это странная конструкция нужна для того, чтобы тесты в постмане прошли.
Если что-то такое встречается, то лучше сразу уточни у наставника.

2024-05-03 17:19 UTC, dgumich commented on src/test/java/ru/practicum/shareit/userTest/UserDtoTest.java
> +     * Как сделать так, чтобы учитывалась валидация?
Валидация - это то, что делает спринг, а тут ты просто тестишь сериализацию/десериализацию объект->json.
У тебя тест правильно сделан, надо только проверок больше добавить (имя, емайл).

2024-05-03 23:03 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +         * Это странная конструкция нужна для того, чтобы тесты в постмане прошли.
Егору я этот момент отнёс. Посмотрим что скажет

2024-05-03 23:05 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
О, это я смотрел как эта штука работает вообще, на вебинаре увидел, что если final поле, то не обязательно ставить @Autowired, спринг сам инициализирует этот бин

2024-05-03 23:05 UTC, ArchieBar commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
Исправил

2024-05-03 23:06 UTC, ArchieBar commented on src/test/java/ru/practicum/shareit/userTest/UserDtoTest.java
> +     * Как сделать так, чтобы учитывалась валидация?
Добавил. Ну и для всех дто объектов тоже добавил тесты :)

2024-05-03 23:10 UTC, ArchieBar commented on src/test/java/ru/practicum/shareit/userTest/UserDtoTest.java
> +     * Как сделать так, чтобы учитывалась валидация?
Единственный момент, который хотелось бы уточнить, это касательно потерь во времени. Объект сериализуется с потерями 2ух знаков. 

Я проверял используя DataTimeFormated с ограничением  до 7 знаков нс, но не уверен, что это правильно.

Беглым взглядом почитал, что это момент именно сериализации и в теории нужно задавать этот момент самостоятельно, если нам нужна точность

2024-05-03 23:23 UTC, ArchieBar commented on src/test/java/ru/practicum/shareit/userTest/UserDtoTest.java
> +     * Как сделать так, чтобы учитывалась валидация?
Ха-ха, а нет, DataTimeFormated не подходит. Причём странно, IDEA требует 7 знаков нс, а на гитхабе тесты просят 6. Закомментировал тесты со временем, пока не понимаю как их исправить. Лучше подожду твоих комментариев :) 

Спасибо

2024-05-03 23:37 UTC, ArchieBar commented
Произошли странные технические шоколадки... Добавил тесты и у меня покрытие стало меньше и гит перестал пропускать ветку... Добавил тесты на одно исключение, это исправило ситуацию, но все же, что-то очень странное, я не понимаю как это работает. Почему тесты в гитхабе другие, как они работают вообще?

2024-05-04 21:21 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
Да, всё так и есть. Если есть конструктор, но нет автовайред, то спринг догадается сам, что надо бин внедрить.
Но даже сами спринги советую ставить аннотацию для на глядности. Это для того, что бы когда другой разработчик откроет код, мог сразу понять, что происходит. Чуть уменьшает "магию" спринга.

2024-05-04 21:29 UTC, dgumich approved these changes

2024-05-04 21:29 UTC, dgumich commented on src/test/java/ru/practicum/shareit/requestTest/RequestDtoTest.java
> +        //assertThat(result).extractingJsonPathStringValue("$.created").isEqualTo(formatter.format(localDateTime));
Сделай просто проверку assertThat(result).hasJsonPathValue("$.created"); и будет ок=)

2024-05-05 08:06 UTC, merged